### ISSUE TITLE
Allow unofficial URL with a warning instead of blocking it

### ISSUE THREAD

**Issue by Boerny41** [fm-sys/snapdrop-android#266]
### Describe the feature

Hi,

I'm hosting my own instance of snapdrop and would like to use the app instead of opening it up in the browser.

Sadly it doesn't seem possible anymore the enter an unoffial URL. Could you maybe just display a warning instead of blocking unknown URLs? 

### Describe alternatives you've considered

Opening snapdrop on a mobile browser. It works, just isn't as nice as using the app.

**Comment by ueen** [comment]
maybe @fm-sys can just share how the verification works, than you can just fix your insatnce, amybe add that to a FAQ in the readme?

**Comment by fm-sys** [comment]
This is the current instance check:

        Document doc = Jsoup.connect(newValue).get();
        assert doc != null;
        
        if (doc.selectFirst(".icon-button[href=\"#about\"]") != null && doc.selectFirst("#about>x-background") != null) {
            // website seems to be similar to snapdrop... The check could be improved of course.
        }

**Comment by ueen** [comment]
Maybe look für `x-peers` that would be more specific/essential?

**Comment by fm-sys** [comment]
> Maybe look für `x-peers` that would be more specific/essential?

Done in 7aca1c8.

**Comment by ueen** [comment]
Awesome! Does that work for your instance @Boerny41 ?

**Comment by fm-sys** [comment]
@Boerny41 you can test this apk if you like:

[snapdrop_for_testing.zip](https://github.com/fm-sys/snapdrop-android/files/10958191/snapdrop_for_testing.zip)

**Comment by Boerny41** [comment]
I've just tried the test apk but it still won't allow me to enter my own URL. To be honest, I didn't really understand what you and ueen were talking about before, so is there anything else I should have done besides installing the apk?

**Comment by Boerny41** [comment]
Sorry, clicked the wrong button, didn't mean to close.

**Comment by fm-sys** [comment]
This app requires some elements inside the html. If they do not exist, the app won't let you choose the URL. Have you entered the URL with http/https?

**Comment by Boerny41** [comment]
Yes, I entered "https://MyURL.de". Next I get a message saying something similar to "This doesn't seem to be a snapdrop instance".

**Comment by fm-sys** [comment]
If you don't want to make your URL public, you could also send a mail to snapdrop-android@googlegroups.com

**Comment by Boerny41** [comment]
I was just adding a new nginx proxy entry to share here when I noticed that my snapdrop instance was using authelia. After creating a new proxy entry without authelia it works fine with the application. 👍 

Would it be possible to somehow use instances protected by authelia in the app? I have no idea how hard it is to implement something like this, so I don't know if I'm asking for far too much, but it would be pretty cool, allowing you to share with devices that are not on the same network.

**Comment by fm-sys** [comment]
> Would it be possible to somehow use instances protected by authelia in the app?

Probably this would be manageable. However there are dozens of snapdrop instances, and if everyone has some extra wishes we'll get a hard time maintaining this app. 

But feel free to fork this repo :)

This app is basically just a webview, so maybe it's enough to change that line to `baseURL = "your_url"`

https://github.com/fm-sys/snapdrop-android/blob/7aca1c8c4d42ff4d7c69d5bc07724bd670b86d96/app/src/main/java/com/fmsys/snapdrop/MainActivity.java#L134

**Comment by ueen** [comment]
> it would be pretty cool, allowing you to share with devices that are not on the same network.

https://pairdrop.net/ is going that, maybe you could just run an instance of that/ (fork of snapdrop)
https://github.com/schlagmichdoch/pairdrop
